[tool.poetry]
name = "fastapi-filters"
version = "0.1.0"
description = "fastapi-filters"
authors = ["Yurii Karabas <1998uriyyo@gmail.com>"]
readme = "README.md"
packages = [{ include = "fastapi_filters" }]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
